%token DRONE PROGRAM_BEGIN PROGRAM_END TYPE_STRING TYPE_FLOAT TYPE_INT TYPE_BOOL RETURN IF ELSE TRUE FALSE WHILE_LOOP
PRINT_STATEMENT OR AND NOT VOID_FUNC WİFİ_IDENTIFIER INCLINE_FUNC INCLINE_FUNC ALTITUDE_FUNC ACCEL_FUNC TEMPR_FUNC
ON_FUNC OFF_FUNC PICTURE_FUNC CAPTURE_FUNC CONNECT_FUNC MAIN_FUNC TIME_FUNC TIMER_FUNC VARIABLE INTEGER
COMMA BELONGS SMALLER_THAN BIGGER_THAN ADD SUBTRACT DIVIDE MULTIPLY LP RP LC RC LSQ END_STATEMENT RSQ SEMI_COL ASGN_OP COMMENT QUOTE